steps:
  # Download .env file
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://sopp-305401/.prod.env", ".env"]
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/mongosopp-api', '.' ]
  # push the container image to gcr
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/${_PROJECT_ID}/mongosopp-api']
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'mongosopp-api', '--image', 'gcr.io/${_PROJECT_ID}/mongosopp-api', '--region', 'europe-west4', '--platform', 'managed', '--allow-unauthenticated']